### ISSUE TITLE
后端开发

### ISSUE THREAD

**Issue by maystarry** [ClementLevi/GoFA-Remake#1]
会有后续开发吗，方便留个联系方式吗

**Comment by ClementLevi** [comment]
> 会有后续开发吗，方便留个联系方式吗

还在打基础，毕竟非科班出身；联系可以邮箱或者QQ1090708360@qq.com

**Comment by maystarry** [comment]
您的邮件已收到，我会尽快查收并处理，谢谢

**Comment by Aisishare** [comment]
项目还在继续吗？

**Comment by maystarry** [comment]
您的邮件已收到，我会尽快查收并处理，谢谢
